print("Initializing...")
os.sleep(0.5)
print("Getting in position...")
os.sleep(0.5)
turtle.up()
os.sleep(1)
turtle.forward()
os.sleep(1.5)
print("In position.")
os.sleep(1)
print("Preparing Inventory...")
shell.run("Refill")