print("Installing Farmer Steve.iso")
print("Copyright: Stennish - 2021")
print("")
print("Designed for: 2 8x16 Farms.")
print("Image: imgur.com/ctxxMas.png")
os.sleep(2.5)
pastebin get GvpLhcDh Replant
pastebin get xvcrmfTs startup
os.sleep(1)
print("Farmer Steve Successfully Installed!")
print("Enjoy your farming!")
os.sleep(1.5)
print("Restarting in 5 seconds...")
os.sleep(5)
os.reboot()