-- You can find the up to date (sometimes broken) code on my github page
-- including my other little projects at github.com/Stennish/ComputerCraft-Scripts/

local function clear()
    shell.run("clear")
end
clear()
fs.delete("startup")
fs.delete("Replant")
textutils.slowPrint("Downloading Farmer Steve.iso...")
os.sleep(0.5)
textutils.slowPrint("Copyright: Stennish - 2021")
os.sleep(1.5)
print("")
print("Designed for: 2 8x16 Farms.")
print("Template: imgur.com/ctxxMas.png")
os.sleep(2.5)
clear()
os.sleep(0.5)
textutils.slowPrint("Downloading...")
os.sleep(1)
print("[|         ]")
os.sleep(0.5)
shell.run("pastebin","get","7jJ8BfR7","Replant")
clear()
print("Downloading...")
print("[|||||     ]")
os.sleep(0.5)
shell.run("pastebin","get","fChmY7q7","startup")
clear()
print("Downloading...")
print("[||||||||||]")
os.sleep(1)
clear()
textutils.slowPrint("Installing...")
os.sleep(1)
print("[          ]")
os.sleep(0.5)
clear()
print("Installing...")
print("[||        ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||      ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||||    ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||||||  ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||||||||]")
os.sleep(1)
clear()
textutils.slowPrint("Farmer Steve Successfully Installed!")
textutils.slowPrint("Enjoy your farming!")
os.sleep(2.5)
clear()
print("Restarting in 5 seconds...")
os.sleep(1)
clear()
print("Restarting in 4 seconds...")
os.sleep(1)
clear()
print("Restarting in 3 seconds...")
os.sleep(1)
clear()
print("Restarting in 2 seconds...")
os.sleep(1)
clear()
print("Restarting in 1 second ...")
os.sleep(1)
clear()
os.sleep(2)
os.reboot()