local function clear()
    shell.run("clear")
end

textutils.slowPrint("Downloading Farmer Steve.iso...")
os.sleep(0.5)
textutils.slowPrint("Copyright: Stennish - 2021")
print("")
print("Designed for: 2 8x16 Farms.")
print("Image: imgur.com/ctxxMas.png")
os.sleep(2.5)
clear()
os.sleep(0.5)
textutils.slowPrint("Downloading...")
print("[|         ]")
shell.run("pastebin","get","7jJ8BfR7","Replant")
os.sleep(0.5)
clear()
print("Downloading...")
print("[|||||     ]")
shell.run("pastebin","get","fChmY7q7","startup")
os.sleep(0.5)
clear()
print("Downloading...")
print("[||||||||||]")
os.sleep(1)
textutils.slowPrint("Installing...")
print("[          ]")
os.sleep(0.5)
clear()
print("Installing...")
print("[||        ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||      ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[IIIIII    ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||||||  ]")
os.sleep(0.25)
clear()
print("Installing...")
print("[||||||||||]")
os.sleep(1)
clear()
textutils.slowPrint("Farmer Steve Successfully Installed!")
textutils.slowPrint("Enjoy your farming!")
os.sleep(2.5)
clear()
print("Restarting in 5 seconds...")
os.sleep(1)
clear()
print("Restarting in 4 seconds...")
os.sleep(1)
clear()
print("Restarting in 3 seconds...")
os.sleep(1)
clear()
print("Restarting in 2 seconds...")
os.sleep(1)
clear()
print("Restarting in 1 second ...")
os.sleep(1)
os.reboot()