print("+------------------------------+")
os.sleep(0.25)
print("|         Farmer Steve         |")
os.sleep(0.25)
print("|  Designed for: 2 8x16 Farms. |")
print("+------------------------------+")
os.sleep(0.25)
print("|     imgur.com/ctxxMas.png    |")
print("+------------------------------+")
os.sleep(1.25)
print("|  Copyright: Stennish - 2021  |")
print("+------------------------------+")
os.sleep(2)
print("|         Instructions         |")
print("|  Fill inventory with seeds,  |")
print("| then run 'Replant' and wait. |")
print("+------------------------------+")