shell.run("clear")
textutils.slowPrint("CraftOS 1.7")
os.sleep(1.5)
shell.run("clear")
os.sleep(0.5)
print("+------------------------------+")
print("|         Farmer Steve         |")
print("|  Designed for: 2 8x16 Farms. |")
print("+------------------------------+")
print("|     imgur.com/ctxxMas.png    |")
print("+------------------------------+")
print("|  Copyright: Stennish - 2021  |")
print("+------------------------------+")
print("|         Instructions         |")
print("|  Fill inventory with seeds,  |")
print("| then type 'Replant' and wait |")
print("+------------------------------+")