print("Preparing to Replant.")
os.sleep(0.5)
print("Refueling...")
turtle.select(16)
os.sleep(0.25)
turtle.refuel()
print("Refueled.")
term.write("Fuel Left" .. turtle.getFuelLevel())
os.sleep(2)
print("Starting.")
os.sleep(1)
